### ISSUE TITLE
Error while trying to run "etheno --ganache"

### ISSUE THREAD

**Issue by dxganta** [crytic/etheno#115]
While trying to run "etheno --ganache" I am getting the following error

INFO     [08-19|20:41:52][Ganache@8546] Cannot wrap string value "109891806170775316617471943642066786755316071364270148407537998213554720155005" as a json-rpc type; strings must be prefixed with "0x".

<img width="1119" alt="Screenshot 2022-08-19 at 8 42 02 PM" src="https://user-images.githubusercontent.com/47485188/185650606-8e31d393-1a49-4af2-8f85-ad7b684e4918.png">

**Comment by anishnaik** [comment]
Hi @dxganta this issue has been fixed in our latest alpha release. You can download it by running the following command:
`pip install etheno==0.3a1`

Note that you will need ganache v0.7.x or greater for the newest version of etheno to work.

**Comment by dxganta** [comment]
Thank You ser
