### ISSUE TITLE
install command not working 

### ISSUE THREAD

**Issue by 0xKarl98** [crytic/etheno#129]
the case is :

when i was trying to install the etheno , using pip3 install etheno command , it shows i have successfully downloaded .

but it got no command of etheno when i type etheno-ganache .

then i solved this issue by running the setup.py manually.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/43113774/216377441-f76dc893-b3db-483d-957c-b7415dde78dd.png">

**Comment by 0xKarl98** [comment]
So probably somewhere in the readme should be changed then .

**Comment by anishnaik** [comment]
Hey @0xKarl98 , thanks for filing the issue. I'm not able to reproduce this unfortunately. What was the command you tried to run after `pip3 install etheno`? Were you using a virtualenv?

**Comment by 0xKarl98** [comment]
hi , this issue is resolved , thanks for support 
i will close this disscution !
