### ISSUE TITLE
Etheno cannot activate Ganache-cli

### ISSUE THREAD

**Issue by BarrySauce** [crytic/etheno#94]
May I know the suitable node version for using Etheno together with Ganache cli? According to the description in Etheno reame.md, I set the node version to node v.12.22.11. And I install ganache-cli to this node. However when I input the command "etheno --ganache" in the terminal, there would always be error as shown in the screenshot below:
<img width="1512" alt="Screenshot 2022-04-11 at 10 17 50 AM" src="https://user-images.githubusercontent.com/84897434/162654258-aa243b9c-e23e-4e95-a79a-23108aa9c575.png">

I tried different version of Ganache-cli, but the same error keeps occurring. May I know what the problem is? 

P.S. When I activate the Ganache-cli in node 12 by running "ganache-cli", there would also be error. So I also tried node v.16.14.0, the Ganache-cli can be activated, but when using together with Etheno, the same error occurs.

**Comment by BarrySauce** [comment]
Hi sir, when I directly run the 'ganache-cli' command in my terminal under node 12, there would be error occurring as below:
<img width="1512" alt="Screenshot 2022-04-13 at 3 08 49 PM" src="https://user-images.githubusercontent.com/84897434/163120050-8c9ceea8-090d-424d-b785-74437073fc18.png">
<img width="1512" alt="Screenshot 2022-04-13 at 3 09 16 PM" src="https://user-images.githubusercontent.com/84897434/163120084-d47b7822-82d7-46b2-86be-34a7d9c98452.png">

**Comment by ggrieco-tob** [comment]
Uhm, interesting. Can you please open an issue showing that error in the ganache repository: https://github.com/trufflesuite/ganache/issues ?

**Comment by BarrySauce** [comment]
@ggrieco-tob Yes sir, I created a discussion post on ganache repo, you can refer to this link: https://github.com/trufflesuite/ganache/discussions/2875
I will switch to node 12.0.0 and try it again 👍

**Comment by BarrySauce** [comment]
@ggrieco-tob Hi sir, I switch to node 12.0.0 and install ganache-cli. Now the ganache-cli can operate properly when I directly activate it. But when I use Etheno, the same error occurs:
<img width="1512" alt="Screenshot 2022-04-13 at 5 37 40 PM" src="https://user-images.githubusercontent.com/84897434/163147856-9600bff6-a1b6-49f3-8e0d-bf850a44851d.png">

So currently it seems there are some problems with Etheno. By the way, after I install Etheno, when I type 'Etheno' in the terminal, it shows 'command not found', I searched on the internet and found the solution is to enter the two commands below:
$ echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
$ source ~/.bashrc
After typing these two command, I can activate Etheno, but still it cannot work with Ganache-cli properly.

Currently the two possible reasons I can think of are:
1. The Ganache-cli I use currently is the newest version v7.0.4, Etheno may not be compatible with this new version.
2. I am currently use python3 version v3.7.8, the pip verison I use is 22.0.4, Etheno may not be compatible with this python 3 version. 
I think the first reason might be more possible, maybe I can try installing older version of ganache (like the version developed 2 years ago).

**Comment by BarrySauce** [comment]
I tried Ganache-cli in my node 16, and used it with Etheno together, it can work properly now
